name: Node CI - klutch

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        app/client/npm ci
        app/client/npm run build --if-present
        app/client/npm test
        app/server/npm ci
        app/server/npm run build --if-present
        app/server/npm test
      env:
        CI: true
